[package]
name = "transformer"
version = "0.1.0"
authors = ["aleics <aleics.casanovas@gmail.com>"]
edition = "2018"

[dependencies]
ebooler = { path = "../ebooler", features = ["serde"] }

# For external trait impls
serde = { version = "1.0.111", default-features = false, optional = true }

[dev-dependencies]
serde_json = "1.0.53"

[package.metadata.docs.rs]
features = ["serde"]
